---
- name: Create the CMES-Pi
  hosts: all
  become: true
  tasks:
      ## We have to split into two steps because when networking changes
      ## DHCP gives out a new IP which breaks Ansible
    - name: Run step1 tasks
      when: step1 is true
      block:
        - name: Patch and reboot system
          ansible.builtin.include_tasks: tasks/patch_system.yml

        - name: Configure wpa_supplicant as access point
          ansible.builtin.include_tasks: tasks/configure_wpa_supplicant.yml

        - name: Configure access point with eth0 on NAT
          ansible.builtin.include_tasks: tasks/configure_access_point.yml

        - name: Configure hostapd
          ansible.builtin.include_tasks: tasks/configure_hostapd.yml

    - name: Run step2 tasks
      when: step2 is true
      block:
        - name: Configure ufw
          ansible.builtin.include_tasks: tasks/configure_ufw.yml

        - name: Configure ssh key
          ansible.builtin.include_tasks: tasks/configure_ssh_key.yml

        - name: Configure fail2ban
          ansible.builtin.include_tasks: tasks/configure_fail2ban.yml

        - name: Configure apache2
          ansible.builtin.include_tasks: tasks/configure_apache2.yml

        - name: Configure php
          ansible.builtin.include_tasks: tasks/configure_php.yml

        - name: Configure cron jobs
          ansible.builtin.include_tasks: tasks/configure_cron.yml

        - name: Configure power management
          ansible.builtin.include_tasks: tasks/configure_power_management.yml

        - name: Clean up pi
          ansible.builtin.include_tasks: tasks/clean_up_pi.yml

  handlers:
    - name: Reboot host
      ansible.builtin.reboot:

    - name: Restart fail2ban
      ansible.builtin.shell: fail2ban-client stop && fail2ban-client start
      changed_when: false

    - name: Restart apache
      ansible.builtin.systemd:
        state: restarted
        name: apache2
