---
- name: Create journalctl log file directory
  ansible.builtin.file:
    path: /var/log/journal
    owner: root
    group: systemd-journal
    mode: '755'
    state: directory
  changed_when: false # next task changes permissions

- name: Create tmp files
  ansible.builtin.command: systemd-tmpfiles --create --prefix /var/log/journal
  changed_when: false

- name: Install rng-tools
  ansible.builtin.apt:
    name: rng-tools
    state: present

- name: Mask networking.service
  ansible.builtin.systemd:
    name: networking
    enabled: false
    masked: true
  notify: Reboot host

- name: Mask avahi-daemon.service
  ansible.builtin.systemd:
    name: avahi-daemon
    enabled: false
    masked: true
  failed_when: false # The service may not exist
  notify: Reboot host

- name: Mask dhcpcd
  ansible.builtin.systemd:
    name: dhcpcd
    enabled: false
    masked: true
  register: result
  until: result is not failed
  retries: 5
  delay: 3
  notify: Reboot host

- name: Disable network/interfaces # This can be better
  ansible.builtin.command: mv /etc/network/interfaces /etc/network/interfaces~
  changed_when: false
  failed_when: false

- name: Add line to resolvconf.conf
  ansible.builtin.lineinfile:
    path: /etc/resolvconf.conf
    regexp: '^resolvconf=.+'
    insertbefore: BOF
    line: 'resolvconf=NO'
    create: true
    owner: root
    group: root
    mode: '0644'
  notify: Reboot host

- name: Enable systemd-networkd.service
  ansible.builtin.systemd:
    name: systemd-networkd
    enabled: true
  notify: Reboot host

- name: Enable systemd-resolved.service
  ansible.builtin.systemd:
    name: systemd-resolved
    enabled: true
  notify: Reboot host

- name: Create symlink for resolv.conf
  ansible.builtin.file:
    path: /etc/resolv.conf
    src: /run/systemd/resolve/resolv.conf
    owner: root
    group: root
    mode: '0644'
    state: link
    follow: false
    force: true
  notify: Reboot host

- name: Create wpa_supplicant@wlan0.service.d directory
  ansible.builtin.file:
    path: /etc/systemd/system/wpa_supplicant@wlan0.service.d/
    owner: root
    group: root
    mode: '755'
    state: directory
  changed_when: false # next task changes permissions

- name: Create NAT Routing for the wpa_supplicant@wlan0.service
  ansible.builtin.copy:
    dest: /etc/systemd/system/wpa_supplicant@wlan0.service.d/override.conf
    owner: root
    group: root
    mode: '0644'
    content: |
      [Service]
      ExecStartPre=/sbin/iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
      ExecStopPost=-/sbin/iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
  notify: Reboot host

- name: Restart systemd-networkd.service
  ansible.builtin.systemd:
    name: systemd-networkd
    enabled: true
  notify: Reboot host