---
- name: Add package
  ansible.builtin.apt:
    name: apache2
    state: present

- name: Copy apache2.conf file
  ansible.builtin.copy:
    src: files/apache2/apache2.conf
    dest: /etc/apache2/apache2.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart apache

- name: Enable the Apache2 modules
  community.general.apache2_module:
    state: present
    name: "{{ item }}"
  loop:
    - headers
    - rewrite
  notify: Restart apache

- name: Copy 000-default.conf file
  ansible.builtin.copy:
    src: files/apache2/000-default.conf
    dest: /etc/apache2/sites-available/000-default.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart apache

- name: Restart apache2 if needed
  ansible.builtin.meta: flush_handlers
