---
- name: Update /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: 127.0.1.1	CMES-Pi-00000
    owner: root
    group: root
    mode: '0644'

- name: Set hostname
  ansible.builtin.hostname:
    name: CMES-Pi-00000
