---
- name: Run the equivalent of "apt-get update"
  ansible.builtin.apt:
    update_cache: true
  changed_when: false

- name: Update system
  ansible.builtin.apt:
    upgrade: full
  notify: Reboot host

- name: Reboot if handler was notified
  ansible.builtin.meta: flush_handlers
